SELECT
    O_ORDERKEY AS ORDER_KEY,
    O_CUSTKEY AS CUSTOMER_KEY,
    O_ORDERSTATUS AS STATUS_CODE,
    O_TOTALPRICE AS TOTAL_PRICE,
    O_ORDERDATE AS ORDER_DATE
FROM 
    {{ source('TPCH','ORDERS') }}
